version: '3.8'

services:
  # Auth Service
  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    image: smart-home-auth-service:${TAG:-latest}
    container_name: auth_service
    ports:
      - "${AUTH_SERVICE_PORT:-3001}:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${AUTH_SERVICE_PORT:-3001}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-energy_monitor}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1d}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Telemetry Service
  telemetry-service:
    build:
      context: ./backend/telemetry-service
      dockerfile: Dockerfile
    image: smart-home-telemetry-service:${TAG:-latest}
    container_name: telemetry_service
    ports:
      - "${TELEMETRY_SERVICE_PORT:-3002}:3002"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-energy_monitor}
    depends_on:
      - auth-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Chat Service
  chat-service:
    build:
      context: ./backend/chat-service
      dockerfile: Dockerfile
    image: smart-home-chat-service:${TAG:-latest}
    container_name: chat_service
    ports:
      - "${CHAT_SERVICE_PORT:-3003}:3003"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-energy_monitor}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - auth-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: smart-home-frontend:${TAG:-latest}
    container_name: energy_monitor_frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - REACT_APP_API_URL=${API_URL:-http://localhost:3001}
      - REACT_APP_CHAT_API_URL=${CHAT_API_URL:-http://localhost:3003}
      - NODE_ENV=${NODE_ENV:-production}
    depends_on:
      - auth-service
      - telemetry-service
      - chat-service
    restart: unless-stopped
